<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17414" started-at="2021-06-23T10:58:33Z" finished-at="2021-06-23T10:58:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="17414" started-at="2021-06-23T10:58:33Z" finished-at="2021-06-23T10:58:51Z">
      <class name="testCases.TC_001">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TC_001@4883b407]" name="launchBrowser" is-config="true" duration-ms="13106" started-at="2021-06-23T10:58:33Z" finished-at="2021-06-23T10:58:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:testCases.TC_001@4883b407]" name="loginTest" duration-ms="2363" started-at="2021-06-23T10:58:46Z" finished-at="2021-06-23T10:58:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.naukri.com/mnjuser/homepage] but found [https://www.naukri.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.naukri.com/mnjuser/homepage] but found [https://www.naukri.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.MenuPages.LoginPage.clickSubmitButton(LoginPage.java:59)
at testCases.TC_001.loginTest(TC_001.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testCases.TC_001@4883b407]" name="closeBrowser" is-config="true" duration-ms="1896" started-at="2021-06-23T10:58:49Z" finished-at="2021-06-23T10:58:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testCases.TC_001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
